'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'id';

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => any; // Returns the localized string or object
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Define our dictionaries for the dashboard and admin areas
const dictionaries = {
  en: {
    dashboard: {
      overview: 'Overview',
      products: 'Products',
      sales: 'Sales',
      settings: 'Settings',
      welcome: 'Welcome back',
    },
    nav: {
      main_menu: 'Main Menu',
      business: 'Business',
      home: 'Home',
      my_link: 'My Store',
      appearance: 'Appearance',
      analytics: 'Analytics',
      add_product: 'Add Product',
      orders: 'Orders',
      customers: 'Customers',
      earnings: 'Earnings',
      settings: 'Settings',
      subscription: 'Subscription',
      logout: 'Logout',
    },
    dashboard_content: {
      share: 'Share',
      add_link: 'Add Link',
      digital_product: 'Digital Product',
      blog_content: 'Blog Content',
      video_course: 'Video Course',
      total_revenue: 'Total Revenue',
      active_customers: 'Active Customers',
      products_sold: 'Products Sold',
      visitor_stats: 'Visitor Statistics',
      live_preview: 'Live Preview',
      store_traffic: 'STORE TRAFFIC LAST 7 DAYS',
      weekly: 'Weekly',
      monthly: 'Monthly',
      main_store_url: 'MAIN STORE URL',
      copy: 'Copy',
      change_slug: 'Change Slug',
      add_new_block: '+ Add New Block',
      active_content_list: 'ACTIVE CONTENT LIST',
      appearance_customization: 'Appearance Customization',
      appearance_desc: 'Customize theme & colors',
      cta_text: 'CTA Button Text',
      cta_text_placeholder: 'Example: Join Community',
      cta_link: 'CTA Button Link',
      theme_brand: 'THEME & BRAND IDENTITY',
      main_theme_color: 'MAIN THEME COLOR',
      typography: 'TYPOGRAPHY (FONT)',
      block_layout: 'BLOCK LAYOUT',
      profile_header: 'Profile & Header',
      profile_photo: 'PROFILE PHOTO',
      header_bg: 'HEADER IMAGE (BACKGROUND)',
      short_bio: 'SHORT DESCRIPTION (BIO)',
      social_links: 'Social Media Links',
      promo_cta: 'Promo & CTA',
      promo_banner: 'PROMO BANNER (IMAGE)',
      content_bg_color: 'CONTENT BACKGROUND COLOR',
      save_appearance: 'Save Appearance',
      live_preview_note: 'Changes are immediately visible in Live Preview',
      performance_analytics: 'Performance Analytics',
      traffic_conv_30d: 'TRAFFIC & CONVERSIONS LAST 30 DAYS',
      total_views: 'TOTAL VIEWS',
      total_clicks: 'TOTAL CLICKS',
      thirty_days: '30 Days',
      ninety_days: '90 Days',
      conversion: 'Conversion',
      waiting_data: 'WAITING FOR VISITOR DATA',
      order_list: 'Order List',
      store_txn_history: 'STORE TRANSACTION HISTORY',
      search_orders: 'Search orders...',
      order_id: 'ORDER ID',
      customer: 'CUSTOMER',
      product: 'PRODUCT',
      status: 'STATUS',
      total: 'TOTAL',
      no_order_history: 'NO ORDER HISTORY YET',
      customer_db: 'Customer Database',
      registered_customers: 'Registered Customers',
      customer_email: 'EMAIL',
      customer_orders: 'ORDERS',
      customer_spent: 'TOTAL SPENT',
      customer_action: 'ACTION',
      no_customer_data: 'NO CUSTOMER DATA YET',
      earnings_payouts: 'Earnings & Payouts',
      withdraw_anytime: 'Withdraw funds instantly anytime',
      available_balance: 'Available Balance',
      payout_settings: 'Payout Settings',
      last_withdrawal: 'LAST WITHDRAWAL',
      instant_payout_active: 'Instant Payout System Active',
      payout_history: 'Payout History',
      all: 'ALL',
      no_withdrawal_history: 'No withdrawal history yet.',
      withdraw_to: 'Withdraw To',
      bank_ewallet: 'BANK / E-WALLET',
      account_number: 'ACCOUNT NUMBER',
      account_holder: 'ACCOUNT HOLDER',
      no_account_yet: 'No Account Yet',
      add_account_desc: 'Add an account to start withdrawing your earnings.',
      add_account: 'Add Account',
      withdrawal_info: 'Withdrawal Information',
      transfer_fee_info: 'Flat transfer fee of Rp 3,500 per withdrawal. Instant Payout system will immediately process funds to your account in seconds.',
      instant_payout: 'Instant Payout',
      withdrawal_amount: 'WITHDRAWAL AMOUNT',
      withdrawal_amount_label: 'Withdrawal Amount',
      instant_payout_fee: 'Instant Payout Fee',
      received_in_account: 'Received in Account',
      withdraw_now: 'Withdraw Now',
      no_bank_warning: 'You have not set up a withdrawal destination account.',
      destination_account: 'Destination Account',
      bank_name_code: 'BANK NAME / XENDIT CODE',
      bank_code_note: 'Ensure the bank code matches the Xendit format.',
      account_holder_name: 'ACCOUNT HOLDER NAME',
      save_account: 'Save Account',
      store_settings: 'Store Settings',
      store_config_desc: 'White-label & General Configuration',
      store_name: 'STORE NAME',
      store_slug: 'STORE SLUG (URL)',
      store_description: 'STORE DESCRIPTION',
      save_changes: 'Save Changes'
    },
    product_modal: {
      add_new: 'Add New Product',
      edit: 'Edit Product',
      setup: 'Setup your digital product',
      step: 'Step',
      of: 'of',
      basic_info: 'Basic Info',
      price_promo: 'Price & Promo',
      done: 'Done',
      title: 'Product Title',
      title_placeholder: 'Example: 2024 Content Strategy Ebook',
      desc: 'Short Description',
      desc_placeholder: 'Explain what buyers will get...',
      cover: 'Cover Image',
      select_image: 'Select Image',
      max_5mb: 'Max 5MB',
      type_delivery: 'Product Type & Delivery',
      type_file: 'Digital File',
      type_file_desc: 'Upload file / PDF',
      type_link: 'Access Link',
      type_link_desc: 'G-Drive / Notion',
      type_booking: 'Consultation',
      type_booking_desc: 'Zoom Session / Live',
      upload_main: 'Upload Main File',
      buyers_download: 'Buyers will download this',
      click_to_select: 'Click to Select File Max 50MB',
      secret_link: 'Secret Access Link',
      cancel: 'Cancel',
      next: 'Next',
      back: 'Back',
      publish: 'Publish Product',
      save_changes: 'Save Changes',
      no_schedule: 'No schedule yet. Add your first slot.',
      session_schedule: 'Session Schedule & Quota',
      determine_availability: 'Determine your availability',
      add_slot: '+ Add Slot',
      session_date: 'Session Date',
      time_start_end: 'Time (Start - End)',
      participant_quota: 'Participant Quota',
      meeting_link: 'Meeting Link (Optional)',
      selling_price: 'Selling Price',
      determine_value: 'Determine your product value',
      main_price: 'Main Price (IDR)',
      original_price: 'Original Price (Optional)',
      pwyw_desc: 'Buyers are free to pay more than the recommended price',
      fomo_desc: 'Show an urgency timer to increase conversion (FOMO)',
      min_price: 'Minimum Price Limit (IDR)',
      pwyw_note: 'By enabling PWYW, the "Main Price" column above becomes a "Recommended Price" for buyers.',
      ends_at: 'Ends At',
      quota_limit: 'Quota Limit (Optional)',
      ready_publish: 'Ready to Publish!',
      ready_desc_1: 'Your product',
      ready_desc_2: 'is ready. You can review it again or save it directly.',
      untitled: 'Untitled',
      quota_placeholder: 'Example: 100',
      success_updated: 'Product updated successfully!',
      success_added: 'Product added successfully!',
      error_updating: 'Failed to update product',
      error_adding: 'Failed to add product',
      title_required: 'Product title is required',
      price_required: 'Price is required',
    },
    admin: {
      overview: 'Platform Overview',
      creators: 'Creators',
      blog: 'Blog CMS',
      settings: 'Settings',
      revenue: 'Total Revenue',
      activeUsers: 'Active Users',
    },
    subscription_page: {
      back_dashboard: 'Back to Dashboard',
      manage_subscription: 'Subscription Management',
      payment_success: 'Payment Successful!',
      payment_success_desc: 'Your subscription package is being activated. Please wait a moment.',
      payment_failed: 'Payment failed or cancelled. Please try again.',
      current_plan: 'CURRENT PLAN',
      current_plan_btn: 'Current Plan',
      starter_desc: 'Free forever. Perfect for trying out your first sales.',
      valid_until: 'Valid until',
      premium_active: 'Premium Active',
      free_active: 'Free Plan Active',
      choose_best: 'Choose Your Best Plan',
      unlock_features: 'Unlock all exclusive features, remove limits, and maximize your store\'s revenue today.',
      starter: 'STARTER',
      forever: '/forever',
      fee_3_percent: '3% transaction fee',
      fee_0_percent: '0% transaction fee',
      subdomain_platform: 'Platform subdomain',
      max_3_products: 'Maximum 3 digital products',
      downgrade: 'Downgrade Plan',
      recommended: 'RECOMMENDED',
      mo: '/mo',
      yr: '/yr',
      subscribe_now: 'Subscribe Now',
      invalid_session: 'Invalid user session, please login again.'
    }
  },
  id: {
    dashboard: {
      overview: 'Ikhtisar',
      products: 'Produk',
      sales: 'Penjualan',
      settings: 'Pengaturan',
      welcome: 'Selamat datang kembali',
    },
    nav: {
      main_menu: 'Menu Utama',
      business: 'Bisnis',
      home: 'Beranda',
      my_link: 'Toko Saya',
      appearance: 'Tampilan',
      analytics: 'Statistik',
      add_product: 'Tambah Produk',
      orders: 'Pesanan',
      customers: 'Pelanggan',
      earnings: 'Pendapatan',
      settings: 'Pengaturan',
      subscription: 'Langganan',
      logout: 'Keluar',
    },
    dashboard_content: {
      share: 'Bagikan',
      add_link: 'Tambah Link',
      digital_product: 'Produk Digital',
      blog_content: 'Blog Konten',
      video_course: 'Video Kursus',
      total_revenue: 'TOTAL PENDAPATAN',
      active_customers: 'PELANGGAN AKTIF',
      products_sold: 'PRODUK TERJUAL',
      visitor_stats: 'Statistik Pengunjung',
      live_preview: 'Tampilan Live',
      store_traffic: 'TRAFFIC TOKO 7 HARI TERAKHIR',
      weekly: 'Mingguan',
      monthly: 'Bulanan',
      main_store_url: 'URL TOKO UTAMA',
      copy: 'Salin',
      change_slug: 'Ubah Slug',
      add_new_block: '+ Tambah Blok Baru',
      active_content_list: 'DAFTAR KONTEN AKTIF',
      appearance_customization: 'Kustomisasi Tampilan',
      appearance_desc: 'Sesuaikan tema & warna',
      cta_text: 'Teks Tombol CTA',
      cta_text_placeholder: 'Contoh: Gabung Komunitas',
      cta_link: 'Link Tombol CTA',
      theme_brand: 'TEMA & IDENTITAS BRAND',
      main_theme_color: 'WARNA TEMA UTAMA',
      typography: 'TIPOGRAFI (FONT)',
      block_layout: 'LAYOUT BLOK',
      profile_header: 'Profil & Header',
      profile_photo: 'FOTO PROFIL',
      header_bg: 'GAMBAR HEADER (BACKGROUND)',
      short_bio: 'DESKRIPSI SINGKAT (BIO)',
      social_links: 'Tautan Sosial Media',
      promo_cta: 'Promosi & CTA',
      promo_banner: 'BANNER PROMOSI (GAMBAR)',
      content_bg_color: 'WARNA LATAR KONTEN',
      save_appearance: 'Simpan Tampilan',
      live_preview_note: 'Perubahan langsung terlihat di Live Preview',
      performance_analytics: 'Analitik Performa',
      traffic_conv_30d: 'TRAFFIC & KONVERSI 30 HARI TERAKHIR',
      total_views: 'TOTAL VIEWS',
      total_clicks: 'TOTAL CLICKS',
      thirty_days: '30 Hari',
      ninety_days: '90 Hari',
      conversion: 'Konversi',
      waiting_data: 'MENUNGGU DATA PENGUNJUNG',
      order_list: 'Daftar Pesanan',
      store_txn_history: 'RIWAYAT TRANSAKSI TOKO',
      search_orders: 'Cari pesanan...',
      order_id: 'ORDER ID',
      customer: 'PELANGGAN',
      product: 'PRODUK',
      status: 'STATUS',
      total: 'TOTAL',
      no_order_history: 'BELUM ADA RIWAYAT PESANAN',
      customer_db: 'Database Pelanggan',
      registered_customers: 'Pelanggan Terdaftar',
      customer_email: 'EMAIL',
      customer_orders: 'PESANAN',
      customer_spent: 'TOTAL BELANJA',
      customer_action: 'AKSI',
      no_customer_data: 'BELUM ADA DATA PELANGGAN',
      earnings_payouts: 'Pendapatan & Pencairan',
      withdraw_anytime: 'Tarik dana instan kapan saja',
      available_balance: 'Saldo Tersedia',
      payout_settings: 'Pengaturan Pencairan',
      last_withdrawal: 'PENARIKAN TERAKHIR',
      instant_payout_active: 'Sistem Instant Payout Aktif',
      payout_history: 'Riwayat Pencairan',
      all: 'SEMUA',
      no_withdrawal_history: 'Belum ada riwayat penarikan.',
      withdraw_to: 'Cairkan Ke',
      bank_ewallet: 'BANK / E-WALLET',
      account_number: 'NOMOR REKENING',
      account_holder: 'ATAS NAMA',
      no_account_yet: 'Belum Ada Rekening',
      add_account_desc: 'Tambahkan rekening untuk mulai menarik dana pendapatanmu.',
      add_account: 'Tambah Rekening',
      withdrawal_info: 'Informasi Penarikan',
      transfer_fee_info: 'Biaya transfer flat Rp 3.500 per penarikan. Sistem Instant Payout akan langsung memproses dana ke rekening Anda dalam hitungan detik.',
      instant_payout: 'Tarik Dana Instan',
      withdrawal_amount: 'NOMINAL PENARIKAN',
      withdrawal_amount_label: 'Nominal Penarikan',
      instant_payout_fee: 'Biaya Instan Payout',
      received_in_account: 'Diterima di Rekening',
      withdraw_now: 'Cairkan Sekarang',
      no_bank_warning: 'Anda belum mengatur rekening tujuan penarikan.',
      destination_account: 'Rekening Tujuan',
      bank_name_code: 'NAMA BANK / KODE XENDIT',
      bank_code_note: 'Pastikan kode bank sesuai dengan format Xendit.',
      account_holder_name: 'NAMA PEMILIK REKENING',
      save_account: 'Simpan Rekening',
      store_settings: 'Pengaturan Toko',
      store_config_desc: 'White-label & Konfigurasi Umum',
      store_name: 'NAMA TOKO',
      store_slug: 'SLUG TOKO (URL)',
      store_description: 'DESKRIPSI TOKO',
      save_changes: 'Simpan Perubahan'
    },
    product_modal: {
      add_new: 'Tambah Produk Baru',
      edit: 'Edit Produk',
      setup: 'Setup produk digital Anda',
      step: 'Langkah',
      of: 'dari',
      basic_info: 'Info Dasar',
      price_promo: 'Harga & Promo',
      done: 'Selesai',
      title: 'Judul Produk',
      title_placeholder: 'Contoh: Ebook Strategi Konten 2024',
      desc: 'Deskripsi Singkat',
      desc_placeholder: 'Jelaskan apa yang pembeli dapatkan...',
      cover: 'Gambar Cover',
      select_image: 'Pilih Gambar',
      max_5mb: 'Maks 5MB',
      type_delivery: 'Tipe & Pengiriman Produk',
      type_file: 'File Digital',
      type_file_desc: 'Upload file / PDF',
      type_link: 'Link Akses',
      type_link_desc: 'G-Drive / Notion',
      type_booking: 'Konsultasi',
      type_booking_desc: 'Sesi Zoom / Live',
      upload_main: 'Upload File Utama',
      buyers_download: 'Pembeli akan mendownload ini',
      click_to_select: 'Klik untuk Pilih File Maks 50MB',
      secret_link: 'Tautan Akses Rahasia',
      cancel: 'Batal',
      next: 'Selanjutnya',
      back: '← Sebelumnya',
      publish: 'Terbitkan Produk',
      save_changes: 'Simpan Perubahan',
      no_schedule: 'Belum ada jadwal. Tambahkan slot pertama Anda.',
      session_schedule: 'Jadwal Sesi & Kuota',
      determine_availability: 'Tentukan ketersediaan Anda',
      add_slot: '+ Tambah Slot',
      session_date: 'Tanggal Sesi',
      time_start_end: 'Jam (Mulai - Selesai)',
      participant_quota: 'Kuota Peserta',
      meeting_link: 'Link Meeting (Opsional)',
      selling_price: 'Harga Jual',
      determine_value: 'Tentukan nilai produk Anda',
      main_price: 'Harga Utama (IDR)',
      original_price: 'Harga Coret / Asli (Opsional)',
      pwyw_desc: 'Pembeli bebas membayar lebih dari harga rekomendasi',
      fomo_desc: 'Munculkan timer urgency untuk meningkatkan konversi (FOMO)',
      min_price: 'Batas Harga Minimum (IDR)',
      pwyw_note: 'Dengan mengaktifkan PWYW, kolom "Harga Utama" di atas akan menjadi "Harga Rekomendasi" bagi pembeli.',
      ends_at: 'Berakhir Pada',
      quota_limit: 'Batas Kuota (Opsional)',
      ready_publish: 'Siap Diterbitkan!',
      ready_desc_1: 'Produk',
      ready_desc_2: 'Anda sudah siap. Anda bisa mereview ulang atau langsung menyimpannya.',
      untitled: 'Tanpa Judul',
      quota_placeholder: 'Contoh: 100',
      success_updated: 'Produk berhasil diperbarui!',
      success_added: 'Produk berhasil ditambahkan!',
      error_updating: 'Gagal memperbarui produk',
      error_adding: 'Gagal menambahkan produk',
      title_required: 'Judul produk wajib diisi',
      price_required: 'Harga wajib diisi',
    },
    admin: {
      overview: 'Ikhtisar Platform',
      creators: 'Kreator',
      blog: 'CMS Blog',
      settings: 'Pengaturan',
      revenue: 'Total Pendapatan',
      activeUsers: 'Pengguna Aktif',
    },
    subscription_page: {
      back_dashboard: 'Kembali ke Dasbor',
      manage_subscription: 'Manajemen Langganan',
      payment_success: 'Pembayaran Berhasil!',
      payment_success_desc: 'Paket berlangganan Anda sedang diaktifkan. Harap tunggu beberapa saat.',
      payment_failed: 'Pembayaran gagal atau dibatalkan. Silakan coba kembali.',
      current_plan: 'PAKET SAAT INI',
      current_plan_btn: 'Paket Saat Ini',
      starter_desc: 'Gratis selamanya. Cocok untuk mencoba jualan pertama Anda.',
      valid_until: 'Berlaku sampai',
      premium_active: 'Premium Aktif',
      free_active: 'Free Plan Aktif',
      choose_best: 'Pilih Paket Terbaikmu',
      unlock_features: 'Buka semua fitur eksklusif, hapus batasan, dan maksimalkan pendapatan toko Anda hari ini juga.',
      starter: 'STARTER',
      forever: '/selamanya',
      fee_3_percent: 'Fee transaksi 3%',
      fee_0_percent: 'Fee transaksi 0%',
      subdomain_platform: 'Subdomain platform',
      max_3_products: 'Maksimal 3 produk digital',
      downgrade: 'Turunkan Paket',
      recommended: 'REKOMENDASI',
      mo: '/bln',
      yr: '/thn',
      subscribe_now: 'Berlangganan Sekarang',
      invalid_session: 'Sesi pengguna tidak valid, silakan login kembali.'
    }
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Language>('en');

  useEffect(() => {
    // Try to load language from localStorage on mount
    const saved = localStorage.getItem('sellora_lang') as Language;
    if (saved === 'en' || saved === 'id') {
      setLangState(saved);
    }
  }, []);

  const setLang = (newLang: Language) => {
    setLangState(newLang);
    localStorage.setItem('sellora_lang', newLang);
  };

  const t = (path: string) => {
    const keys = path.split('.');
    let result: any = dictionaries[lang as keyof typeof dictionaries];
    for (const key of keys) {
      if (result && result[key as keyof typeof result] !== undefined) {
        result = result[key as keyof typeof result];
      } else {
        return path; // fallback to key path if not found
      }
    }
    return result;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
